### ISSUE TITLE
Listen error

### ISSUE THREAD

**Issue by rg3915** [mmistakes/hpstr-jekyll-theme#132]
Hi. I download your project and run jekyll. Return this error.

```
WARN: Unresolved specs during Gem::Specification.reset:
      listen (~> 3.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /home/rg3915/jekyll/hpstr-jekyll-theme/_config.yml
/usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:30:in `require': cannot load such file -- jekyll-sitemap (LoadError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:30:in `block in require_gems'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:27:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:27:in `require_gems'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:97:in `setup'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:49:in `initialize'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `process'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.0.1/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /usr/local/lib/ruby/gems/2.3.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /usr/local/lib/ruby/gems/2.3.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.0.1/bin/jekyll:17:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

**Comment by mmistakes** [comment]
Did you run `bundle install` to install all of the required gems? Looks like `jekyll-sitemap` is missing.
Also you need to run Jekyll via Bundler to properly load all of the correct gem versions.

`bundle exec jekyll serve` to start the server
and `bundle exec jekyll build` to build. Basically it's all of the standard Jekyll commands prepended with `bundle exec`.

**Comment by rg3915** [comment]
Thank you.
